sudo: required
dist: trusty
matrix:
  include:
    - language: python
      python: 2.7
      before_install:
        - cd deployment
      install:
        - pip install paramiko pyyaml jinja2 python-etcd kubernetes
      script:
        - python -m unittest discover test/

    - language: python
      python: 3.6
      before_install:
        - cd src/watchdog/test
      install:
        - pip install paramiko pyyaml requests prometheus_client twisted
      script:
        - python -m unittest discover .

    - language: python
      python: 2.7
      install:
      - pip install paramiko pyyaml jinja2 python-etcd kubernetes GitPython
      script:
      - python -m unittest deployment.clusterObjectModel.test.test_cluster_object_model

    - language: python
      python: 2.7
      install:
      - pip install paramiko pyyaml jinja2 python-etcd kubernetes GitPython
      script:
      - python -m unittest deployment.clusterObjectModel.test.test_template_generate

    - language: python
      python: 2.7
      install:
        - pip install paramiko pyyaml jinja2 python-etcd kubernetes GitPython
      script:
        - python -m unittest deployment.clusterObjectModel.test.test_forward_compatibility

    - language: python
      python: 3.6
      before_install:
        - cd src/job-exporter/test
      install:
        - pip install prometheus_client
      script:
        - python3 -m unittest discover .

    - language: python
      python: 3.6
      before_install:
        - cd src/yarn-exporter/test
      install:
        - pip install prometheus_client twisted requests
      script:
        - python3 -m unittest discover .

    - language: python
      python: 2.7
      install:
        - pip install markdown==2.6.11
      script:
        - python src/utilities/doc_checker.py .

    - language: java
      jdk: oraclejdk8
      before_install:
        - cd subprojects/frameworklauncher/yarn
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - mvn clean test jacoco:report

    - language: java
      jdk: openjdk8
      before_install:
        - cd subprojects/frameworklauncher/yarn
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - mvn clean test jacoco:report

    - language: node_js
      node_js: lts/carbon
      env: NODE_ENV=test
      before_install:
        - cd src/rest-server
      install:
        - yarn install
      script:
        - npm test

    - language: node_js
      node_js: lts/dubnium
      env: NODE_ENV=test
      before_install:
        - cd src/rest-server
      install:
        - yarn install --ignore-engines
      script:
        - npm test

    - language: node_js
      node_js: lts/carbon
      before_install:
        - cd src/webportal
      install:
        - yarn install
        - npm run build
      script:
        - npm test

    - language: node_js
      node_js: lts/dubnium
      before_install:
        - cd src/webportal
      install:
        - yarn install --ignore-engines
        - npm run build
      script:
        - npm test

    - language: node_js
      node_js: node
      before_install: cd contrib/submit-simple-job
      install: npm install
      script: npm test

    - language: node_js
      node_js: lts/dubnium
      before_install: cd contrib/submit-job-v2
      install: yarn --frozen-lockfiles
      script: yarn build

    - language: node_js
      node_js: lts/dubnium
      before_install: cd contrib/marketplace
      install: yarn --frozen-lockfiles
      script: yarn build
