name: Lint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docs:
    name: Lint docs
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown==2.6.11
    - name: Lint
      run: |
        python src/utilities/doc_checker.py .
